version: '3'

services:
  glances:
    image: nicolargo/glances:latest-full
    container_name: glances
    restart: unless-stopped
    expose:
      - "61208"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - "GLANCES_OPT=-w"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.glances.rule=Host(`sys.${DOMAIN}`)"
      - "traefik.http.routers.glances.entrypoints=websecure"
      - "traefik.http.routers.glances.tls.certresolver=le"
      - "traefik.http.services.glances.loadbalancer.server.port=61208"
      # Authelia middleware
      - "traefik.http.routers.glances.middlewares=authelia@docker"