version: '3.8'
services:
  jellyfin-external:
    image: nginx:alpine
    container_name: jellyfin-external
    restart: unless-stopped
    command: >
      /bin/sh -c "echo 'server { 
        listen 80;
        location / { 
          proxy_pass http://192.168.1.10:8096;
          proxy_set_header Host $$host;
          proxy_set_header X-Real-IP $$remote_addr;
          proxy_set_header X-Forwarded-For $$proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto $$scheme;
          
          # WebSocket support
          proxy_http_version 1.1;
          proxy_set_header Upgrade $$http_upgrade;
          proxy_set_header Connection "upgrade";
        }
      }' > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jellyfin.rule=Host(`${JELLYFIN_SUBDOMAIN}.${DOMAIN}`)"
      - "traefik.http.routers.jellyfin.entrypoints=websecure"
      - "traefik.http.routers.jellyfin.tls=true" 
      - "traefik.http.routers.jellyfin.tls.certresolver=le"
    networks:
      - default

networks:
  default:
    name: proxy
    external: true