# traefik‑proxy/docker-compose.yml
version: "3.8"

services:
  traefik:
    image: traefik:v2.10
    container_name: traefik
    restart: unless-stopped
    env_file:
      - .env
    # publish ports for HTTP → ACME challenge & HTTPS
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik.yml:/etc/traefik/traefik.yml:ro
      - ./acme.json:/letsencrypt/acme.json
    # override only the email setting via CLI flag
    command:
      - "--certificatesResolvers.le.acme.email=${ACME_EMAIL}"
