# traefik‑proxy/docker-compose.yml
version: "3.8"
services:
  traefik:
    image: traefik:v2.10
    container_name: traefik
    restart: unless-stopped
    # publish ports for HTTP → ACME challenge & HTTPS
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik.yml:/etc/traefik/traefik.yml:ro
      - ./acme.json:/letsencrypt/acme.json
    # Command with detailed configuration for production certificates
    command:
      - "--log.level=INFO"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      # ACME configuration for production
      - "--certificatesResolvers.le.acme.email=${ACME_EMAIL}"
      - "--certificatesResolvers.le.acme.storage=/letsencrypt/acme.json"
      - "--certificatesResolvers.le.acme.caserver=https://acme-v02.api.letsencrypt.org/directory"
      - "--certificatesResolvers.le.acme.httpchallenge=true"
      - "--certificatesResolvers.le.acme.httpchallenge.entrypoint=web"
