# traefik-proxy/traefik/traefik.yml

log:
  level: INFO

entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false

certificatesResolvers:
  le:
    acme:
      # email is now injected via the CLI flag in docker-compose.yml
      storage: /letsencrypt/acme.json
      httpChallenge:
        entryPoint: web
