# traefik-proxy/traefik/traefik.yml

log:
  level: INFO

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: ":443"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false

certificatesResolvers:
  le:
    acme:
      # email is now injected via the CLI flag in docker-compose.yml
      storage: /letsencrypt/acme.json
      httpChallenge:
        entryPoint: web

# Default TLS options
# tls:
#   options:
#     default:
#       minVersion: VersionTLS12
