version: '3.8'

# A simplified setup for just testing basic connectivity without HTTPS
services:
  traefik:
    image: traefik:v2.10
    container_name: traefik-staging
    ports:
      - "8080:80"  # HTTP port on 8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    command:
      - "--log.level=INFO"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"

  authelia:
    image: authelia/authelia:latest
    container_name: authelia-staging
    volumes:
      - ../authelia/config:/config
      - ../authelia/entrypoint.sh:/entrypoint.sh
    entrypoint: ["/bin/sh", "/entrypoint.sh"]
    environment:
      - TZ=UTC
      - DOMAIN=${DOMAIN}
      - AUTHELIA_JWT_SECRET=${AUTHELIA_JWT_SECRET}
      - AUTHELIA_SESSION_SECRET=${AUTHELIA_SESSION_SECRET}
      - AUTHELIA_STORAGE_ENCRYPTION_KEY=${AUTHELIA_STORAGE_ENCRYPTION_KEY}
      - AUTHELIA_USER_PASSWORD_HASH=${AUTHELIA_USER_PASSWORD_HASH}
      - AUTHELIA_USER_EMAIL=${AUTHELIA_USER_EMAIL}
      - AUTHELIA_SUBDOMAIN=${AUTHELIA_SUBDOMAIN}
      - DASHBOARD_SUBDOMAIN=${DASHBOARD_SUBDOMAIN}
      - GLANCES_SUBDOMAIN=${GLANCES_SUBDOMAIN}
      - JELLYFIN_SUBDOMAIN=${JELLYFIN_SUBDOMAIN}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.authelia-simple.rule=Host(`${AUTHELIA_SUBDOMAIN}.${DOMAIN}`)"
      - "traefik.http.routers.authelia-simple.entrypoints=web"
      - "traefik.http.services.authelia-simple.loadbalancer.server.port=9091"

  glances:
    image: nicolargo/glances:latest-full
    container_name: glances-staging
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - "GLANCES_OPT=-w"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.glances-simple.rule=Host(`${GLANCES_SUBDOMAIN}.${DOMAIN}`)"
      - "traefik.http.routers.glances-simple.entrypoints=web"
      - "traefik.http.services.glances-simple.loadbalancer.server.port=61208"

  dashboard:
    image: traefik/whoami
    container_name: dashboard-staging
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dashboard-simple.rule=Host(`${DASHBOARD_SUBDOMAIN}.${DOMAIN}`)"
      - "traefik.http.routers.dashboard-simple.entrypoints=web"

networks:
  default:
    name: proxy-staging-simple
    external: false