version: '3.8'
services:
  traefik:
    extends:
      file: ./traefik/docker-compose.yml
      service: traefik
    env_file:
      - /etc/secrets/.docker
  glances:
    extends:
      file: ./glances/docker-compose.yml
      service: glances
networks:
  default:
    name: proxy
    external: false
