version: '3.8'
services:
  traefik:
    extends:
      file: ./traefik/docker-compose.yml
      service: traefik
  authelia:
    extends:
      file: ./authelia/docker-compose.yml
      service: authelia
    depends_on:
      - traefik
  glances:
    extends:
      file: ./glances/docker-compose.yml
      service: glances
    depends_on:
      - traefik
      - authelia
  jellyfin:
    extends:
      file: ./external-services/docker-compose.yml
      service: jellyfin-external
    depends_on:
      - traefik
  dashboard:
    image: traefik/whoami
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dashboard.rule=Host(`${DASHBOARD_SUBDOMAIN}.${DOMAIN}`)"
      - "traefik.http.routers.dashboard.entrypoints=websecure"
      - "traefik.http.routers.dashboard.tls=true"
      - "traefik.http.routers.dashboard.tls.certresolver=le"
    restart: unless-stopped
networks:
  default:
    name: proxy
    external: false
