version: '3.8'
services:
  traefik:
    extends:
      file: ./traefik/docker-compose.yml
      service: traefik
  authelia:
    extends:
      file: ./authelia/docker-compose.yml
      service: authelia
    depends_on:
      - traefik
  glances:
    extends:
      file: ./glances/docker-compose.yml
      service: glances
    depends_on:
      - traefik
      - authelia
networks:
  default:
    name: proxy
    external: false
