version: '3.8'

services:
  wireguard:
    image: lscr.io/linuxserver/wireguard:latest
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=${WIREGUARD_PUID}
      - PGID=${WIREGUARD_PGID}
      - TZ=${TZ}
      - SERVERURL=${WIREGUARD_SUBDOMAIN}.${DOMAIN}
      - SERVERPORT=${WIREGUARD_PORT}
      - PEERS=${WIREGUARD_PEERS}
      - PEERDNS=${WIREGUARD_PEERDNS}
      - INTERNAL_SUBNET=${WIREGUARD_INTERNAL_SUBNET}
      - ALLOWEDIPS=${WIREGUARD_ALLOWEDIPS}
      - LOG_CONFS=${WIREGUARD_LOG_CONFS}
    volumes:
      - ./config:/config
      - /lib/modules:/lib/modules
    restart: unless-stopped
    ports:
      - ${WIREGUARD_PORT}:${WIREGUARD_PORT}/udp