---
theme: light

# Only use the identity_validation section for jwt_secret (remove deprecated top-level jwt_secret)
identity_validation:
  reset_password:
    jwt_secret: ${AUTHELIA_JWT_SECRET}

server:
  address: tcp://0.0.0.0:9091

log:
  level: info

totp:
  issuer: Authelia
  period: 30
  skew: 1

# WebAuthn configuration for passkeys/security keys
webauthn:
  display_name: Authelia
  attestation_conveyance_preference: indirect
  selection_criteria:
    user_verification: preferred
  timeout: 60s

authentication_backend:
  file:
    path: /config/users_database.yml.runtime
    password:
      algorithm: argon2id
      iterations: 1
      key_length: 32
      salt_length: 16
      memory: 128
      parallelism: 8

access_control:
  default_policy: two_factor  # Changed from 'deny' to valid default policy
  rules:
    - domain: "authelia.${DOMAIN}"
      policy: bypass
    # Add rules for each domain you want to protect
    - domain: "sys.${DOMAIN}"
      policy: two_factor

session:
  name: authelia_session
  secret: ${AUTHELIA_SESSION_SECRET}
  expiration: 3600  # 1 hour
  inactivity: 300  # 5 minutes
  cookies:
    - domain: ${DOMAIN}
      same_site: lax
      authelia_url: https://authelia.${DOMAIN}
      default_redirection_url: https://out.${DOMAIN}

regulation:
  max_retries: 3
  find_time: 120
  ban_time: 300

storage:
  encryption_key: ${AUTHELIA_STORAGE_ENCRYPTION_KEY}
  local:
    path: /config/db.sqlite3

notifier:
  filesystem:
    filename: /config/notification.txt