---
# User credentials are supplied from environment variables
users:
  user:
    displayname: "Example User"
    # Password hash format must match argon2id algorithm specified in configuration.yml
    password: "${AUTHELIA_USER_PASSWORD_HASH}"
    email: "${AUTHELIA_USER_EMAIL}"
    groups:
      - admins
