version: '3.8'
services:
  dns-setup:
    image: python:3.9-slim
    container_name: dns-setup
    restart: "no"
    volumes:
      - ./dns-setup.py:/app/dns-setup.py
    working_dir: /app
    command: sh -c "pip install requests && python dns-setup.py"
    environment:
      - CLOUDFLARE_API_TOKEN=${CLOUDFLARE_API_TOKEN}
      - CLOUDFLARE_EMAIL=${CLOUDFLARE_EMAIL}
      - CLOUDFLARE_ZONE_ID=${CLOUDFLARE_ZONE_ID}
      - DOMAIN=${DOMAIN}
      - DASHBOARD_SUBDOMAIN=${DASHBOARD_SUBDOMAIN}
      - AUTHELIA_SUBDOMAIN=${AUTHELIA_SUBDOMAIN}
      - GLANCES_SUBDOMAIN=${GLANCES_SUBDOMAIN}
      - JELLYFIN_SUBDOMAIN=${JELLYFIN_SUBDOMAIN}
      - WIREGUARD_SUBDOMAIN=${WIREGUARD_SUBDOMAIN}